apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  selector:
   matchLabels:
    app: pgadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:

        - name: pgadmin-container
          image: dpage/pgadmin4
          env:
           - name: PGADMIN_DEFAULT_EMAIL
             value: "m.karacaaslan2015@gmail.com"
           - name: PGADMIN_DEFAULT_PASSWORD
             value: "admin"
           - name: PGADMIN_CONFIG_SERVER_MODE   
             value: 'False'

          ports:
            - containerPort: 80
              name: pgadminport
